#!/bin/bash
#Generated by JetBrains Toolbox 2.5.2.35332 at 2025-01-17T23:42:47
set -euo pipefail

declare -a intellij_args=()
declare -- wait=""

for o in "$@"; do
	if [[ "$o" = "--wait" || "$o" = "-w" ]]; then
		wait="-W"
		o="--wait"
	fi
	if [[ "$o" =~ " " ]]; then
		intellij_args+=("\"$o\"")
	else
		intellij_args+=("$o")
	fi
done

export PATH="$HOME/.rustup/toolchains/esp-nightly/xtensa-esp-elf/esp-14.2.0_20240906/xtensa-esp-elf/bin:$PATH"
export LIBCLANG_PATH="$HOME/.rustup/toolchains/esp-nightly/xtensa-esp32-elf-clang/esp-18.1.2_20240912/esp-clang/lib"
export CLANG_PATH="$HOME/.rustup/toolchains/esp-nightly/xtensa-esp32-elf-clang/esp-18.1.2_20240912/esp-clang/bin/clang"

open -na "$HOME/Applications/RustRover.app/Contents/MacOS/rustrover" $wait --args "${intellij_args[@]}"
