#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

cd "$(dirname "$0")/.."

script/bootstrap

echo "==> Setting up dotfiles…"
env RCRC=$HOME/.dotfiles/rcrc rcup

echo "==> Dotfiles now ready to go!"
